---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 8/4/2018 18:40
---
local config = module("cfg/utils/currency")

vRP.currency = {}
vRP.currencySpecial = {}


function vRP.currencyUpdater()
    local currencyTime = vRP.getSCurrencyTime("vRP:currency")
    if currencyTime then
        if os.time() >= currencyTime + config.currencyReset*60 then
            vRP.updateCurrency()
            vRP.updateCurrencyEspecials()
            for i=1, #vRP.currency do
                vRP.currency[i]:removeSelf() -- Optional Display Object Removal
                vRP.currency[i] = nil        -- Nil Out Table Instance
            end
            for i=1, #vRP.currencySpecial do
                vRP.currencySpecial[i]:removeSelf() -- Optional Display Object Removal
                vRP.currencySpecial[i] = nil        -- Nil Out Table Instance
            end
            vRP.getCurrency()
        end
    else
        vRP.updateCurrency()
        vRP.updateCurrencyEspecials()
    end
end

function vRP.updateCurrency()
    local url = "http://www.floatrates.com/daily/BRL.json"
    local method = "GET"
    PerformHttpRequest(url, function(code, result, headers)
        vRP.setSCurrency("vRP:currency", result)
        cb(0, nil)
    end, method)
end

function vRP.updateCurrencyEspecials()
    local url = "data.fixer.io/api/latest?access_key=" .. config.fixerApikey
    local method = "GET"
    PerformHttpRequest(url, function(code, result, headers)
        vRP.setSCurrency("vRP:currencyspecial", result)
        cb(0, nil)
    end, method)
end

function vRP.setSCurrency(key, value)
    local time = os.time()
    vRP.execute("vRP/set_srvcurrency",{key = key, value = value, last_time_update = time})
end

function vRP.getSCurrency(key, cbr)
    local rows = vRP.query("vRP/get_srvcurrency",{key = key})
    if #rows > 0 then
        return rows[1].dvalue
    else
        return ""
    end
end

function vRP.getSCurrencyTime(key, cbr)
    local rows = vRP.query("vRP/get_srvcurrency_time",{key = key})
    if #rows > 0 then
        return rows[1].last_time_update
    else
        return false
    end
end
