---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 8/7/2018 02:07
---
local lang = tvRP.clientlang

local cfg = module("cfg/stores/barbershop")
local custom = cfg.default

function tvRP.setOverlay(data)
    if data then
        custom = data
    end
end

function tvRP.getOverlay()
    return custom
end

function tvRP.setOverlay(data)
    if data then
        custom = data
    end
end

function tvRP.getOverlay()
    return custom
end

function tvRP.getDrawables(part)
    if part == 12 then
        return tonumber(GetNumberOfPedDrawableVariations(GetPlayerPed(-1),2))
    elseif part == -1 then
        return tonumber(GetNumberOfPedDrawableVariations(GetPlayerPed(-1),0))
    elseif part == -2 then
        return 64
    else
        return tonumber(GetNumHeadOverlayValues(part))
    end
end

function tvRP.getTextures(part)
    if part == -1 then
        return tonumber(GetNumHairColors())
    else
        return 64
    end
end

Citizen.CreateThread(function()
    while true do
        Citizen.Wait(1)
        while not IsPedModel(GetPlayerPed(-1),"mp_m_freemode_01") and not IsPedModel(GetPlayerPed(-1),"mp_f_freemode_01") do
            Citizen.Wait(1)
        end
        if custom then
            local ped = GetPlayerPed(-1)
            if custom["-1"] then
                SetPedHeadBlendData(ped,custom["-1"][1],custom["-1"][1],custom["-1"][1],custom["-1"][2],custom["-1"][2],custom["-1"][2],1.0,0.0,0.0,false)
            else
                SetPedHeadBlendData(ped,0,0,0,0,0,0,1.0,0.0,0.0,false)
            end
            -- parts
            for k,v in pairs(custom) do
                if tonumber(k) == -1 then
                elseif tonumber(k) == -2 then
                    SetPedEyeColor(ped,v[2])
                elseif tonumber(k) == 12 then
                    SetPedComponentVariation(ped, 2, v[1], 0, 0)
                    SetPedHairColor(ped, v[2], v[2])
                elseif tonumber(k) == 1 or tonumber(k) == 2 or tonumber(k) == 10 then
                    SetPedHeadOverlayColor(ped, tonumber(k), 1, v[2], v[2])
                    SetPedHeadOverlay(ped, tonumber(k), v[1], 1.0)
                elseif tonumber(k) == 5 or tonumber(k) == 8 then
                    SetPedHeadOverlayColor(ped, tonumber(k), 2, v[2], v[2])
                    SetPedHeadOverlay(ped, tonumber(k), v[1], 1.0)
                else
                    SetPedHeadOverlayColor(ped, tonumber(k), 0, v[2], v[2])
                    SetPedHeadOverlay(ped, tonumber(k), v[1], 1.0)
                end
            end
        end
    end
end)