---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 8/9/2018 02:11
---

local custom = {}

function tvRP.setTattoos(data)
    ClearPedDecorations(GetPlayerPed(-1))
    if data then
        custom = data
    end
end

function tvRP.addTattoo(tattoo,store,price)
    ClearPedDecorations(GetPlayerPed(-1))
    if tattoo and store then
        custom[tattoo] = {store,price}
    end
end

function tvRP.delTattoo(tattoo)
    ClearPedDecorations(GetPlayerPed(-1))
    if tattoo then
        custom[tattoo] = nil
    end
end

function tvRP.getTattoos()
    return custom
end


function tvRP.cleanPlayer()
    ClearPedDecorations(GetPlayerPed(-1))
    custom = {}
end

Citizen.CreateThread(function()
    while true do
        Citizen.Wait(1)
        while not IsPedModel(GetPlayerPed(-1),"mp_m_freemode_01") and not IsPedModel(GetPlayerPed(-1),"mp_f_freemode_01") do
            Citizen.Wait(1)
        end
        if custom then
            local ped = GetPlayerPed(-1)
            -- parts
            for k,v in pairs(custom) do
                ApplyPedOverlay(GetPlayerPed(-1), GetHashKey(v[1]), GetHashKey(k))
            end
        end
    end
end)