---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 8/5/2018 13:57
---

local serverlang ={
    db = {
        table_init = "[{1}] init base tables",
        db_connected = "[{1}] Connected to DB using driver \"{2}\".",
        db_connection_fail = "[{1}] Connection to DB failed using driver \"{2}\".",
        db_register = "[{1}] DB driver \"{2}\" already registered.",
        query_not_exist = "[{1}] query {2} doesn't exist.",
        query_debug = "query {1} ({2}) params = ",
        db_config_driver = "[{1}] Missing DB config driver.",
        db_not_initialized = "[{1}] DB driver \"{2}\" not initialized yet ({3} prepares cached, {4} queries cached).",
    },
    admin = {
        ban = "[{1}] BANNED {2} "
    },
    connection = {
        disconnected = "[{1}] {2} disconnected (user_id = {3})",
        ping_timeout = "[{1}] Ping timeout.",
        join = "[{1}] {2} ({3}) joined (user_id = {4})",
        re_join = "[{1}] {2} ({3}) re-joined (user_id = {4})",
        notwhitelisted = "[{1}] {2} ({3}) rejected: not whitelisted (user_id = {4})",
        banned = "[{1}] {2} ({3}) rejected: banned (user_id = {5})",
        ident_error = "[{1}] {2} ({3}) rejected: identification error",
        miss_id = "[{1}] {2} ({3}) rejected: missing identifiers"
    },
    debug = {
        tag = "[{1}] Debug ",
        save_datatbles = "save datatables",
    },
    deferrals = {
        checking_id = "[{1}] Checking identifiers...",
        checking_banned = "[{1}] Checking banned...",
        checking_whitelist = "[{1}] Checking whitelisted...",
        checking_load_db = "[{1}] Loading datatable...",
        get_last_login = "[{1}] Getting last login...",
        notwhitelist = "[{1}] Not whitelisted (user_id = {2}).",
        banned = "[{1}] Banned (user_id = {2}).",
        ident_error = "[{1}] Identification error.",
        miss_id = "[{1}] Missing identifiers."
    },





}
return serverlang