---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 10/5/2018 21:03
---


function vRP.hasNearByPlayer(player)
    local player = vRPclient.getNearestPlayer(player,5)
    if player then
        return true
    end
    return false
end