---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 8/31/2018 14:45
---

local cfg = {}

cfg.market_types = {
    ["Teste"] = {
        _config = {blipid=52, blipcolor=2},
        ["milk"] = 2,
    }
}

cfg.markets = {
    {"Teste",1966.3658447266,3703.4638671875,32.262638092041}

}


return cfg
