---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 8/9/2018 04:14
---

function tvRP.cleanVehicle()
    SetVehicleDirtLevel(GetVehiclePedIsIn(GetPlayerPed(-1),false), 0.0)
    SetVehicleUndriveable(GetVehiclePedIsIn(GetPlayerPed(-1),false), false)
end

function tvRP.getDirtLevel()
    return GetVehicleDirtLevel(GetVehiclePedIsIn(GetPlayerPed(-1),false))
end

function tvRP.isInAnyVehicle()
    local veh = GetVehiclePedIsIn(GetPlayerPed(-1))  -- pega o veiculo
    if veh then  -- se tiver em veiculo
        local driver = GetPedInVehicleSeat(veh, -1) -- pega o motorista do vieculo
        if driver == GetPlayerPed(-1) then  -- se o motorista for o meu ped
            return true
        end
    end
    return false
end