---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 8/3/2018 05:38
---

local function ch_tptowaypoint(player,choice)
    local user_id = vRP.getUserId(player)
    if user_id then
        vRPclient._tpToWayPoint(player)
    end
end

local function ch_blips(player,choice)
    local user_id = vRP.getUserId(player)
    if user_id then
        vRPclient._showBlips(player)
    end
end

local function ch_deleteveh(player,choice)
    local user_id = vRP.getUserId(player)
    if user_id then
        vRPclient._deleteVehicleInFrontOrInside(player,5.0)
    end
end

local function ch_godmode(player,choice)
    local user_id = vRP.getUserId(player)
    if user_id ~= nil then
        if gods[player] then
            gods[player] = nil
            vRPclient._notify(player,"GOD MOD OFF")
        else
            gods[player] = user_id
            vRPclient._notify(player,"GOD MOD ON")
        end
    end
end

local function ch_spawnveh(player,choice)
    local model = vRP.prompt(player,"SPAWNAR CARRO","")
    if modle ~= nil and model ~= "" then
        vRPclient._spawnVehicle(player,model)
    else
        vRPclient._notify(player,"VALOR INVALIDO")
    end
end

