---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 8/3/2018 03:46
---
local config = module("cfg/base")
local time_file_format = os.date("%d-%m-%Y")

function vRP.makeLogFolders()
    os.execute("mkdir ServerLog\\AntiRP_REPORTS")
    os.execute("mkdir ServerLog\\Weapons_Shot")
    os.execute("mkdir ServerLog\\Player\\LoginHistory")
    os.execute("mkdir ServerLog\\Player\\kills")
    os.execute("mkdir ServerLog\\Player\\money")
    os.execute("mkdir ServerLog\\Player\\jobs")
    os.execute("mkdir ServerLog\\Player\\police_weapons_get")
    os.execute("mkdir ServerLog\\Player\\jail")
    os.execute("mkdir ServerLog\\chat\\global")
    os.execute("mkdir ServerLog\\chat\\twitter")
    os.execute("mkdir ServerLog\\chat\\occ")
    os.execute("mkdir ServerLog\\Police\\police_weapons_get")
    os.execute("mkdir ServerLog\\Police\\jail")
end

function vRP.logInfoToFile(file,info)
    file = io.open(file,"a")
    if file then
        file:write(os.date("%c").."=> "..info.. "\n")
    end
    file:close()
end

function vRP.logWeaponsShot(user_id,weapons,location)
    local file = io.open(config.cfg.home_dir.."/ServerLog/Weapons_shot"..time_file_format..".txt","a")
    if file then
        file:write("["..os.date("%c")"] ID: "..user_id.."has shoting with "..weapons.." in "..location .."\n")
    end
    file:close()
end
--todo Implementacao
function vRP.logAntiRPReport() end

function vRP.logPlayerLoginHistory() end

function vRP.logPlayerKills() end

function vRP.logPlayerMoney() end

function vRP.logPlayerJobs() end

function vRP.logPlayerPoliceWeaponsGet() end

function vRP.logPlayerJail() end

function vRP.logChatGlobal() end

function vRP.logChatTwitter() end

function vRP.logChatOCC() end

function vRP.logPoliceWeaponsGet() end

function vRP.logPoliceSendJail() end