---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 8/4/2018 13:12
---

local function ch_userlist(player,choice)
    local user_id = vRP.getUserId(player)
    if user_id ~= nil then
        if player_lists[player] then -- hide
            player_lists[player] = nil
            vRPclient.removeDiv(player,"user_list")
        else -- show
            local content = "<span class=\"id\">"..lang.userlist.id().."</span><span class=\"pseudo\">"..lang.userlist.nickname().."</span><span class=\"name\">"..lang.userlist.rpname().."</span><span class=\"job\">"..lang.userlist.job().."</span>"
            local count = 0
            local users = vRP.getUsers()
            for k,v in pairs(users) do
                count = count+1
                local source = vRP.getUserSource(k)
                local identity = vRP.getUserIdentity(k)
                if source ~= nil then
                    content = content.."<br /><span class=\"id\">"..k.."</span><span class=\"pseudo\">"..vRP.getPlayerName(source).."</span>"
                    if identity then
                        content = content.."<span class=\"name\">"..htmlEntities.encode(identity.firstname).." "..htmlEntities.encode(identity.name).."</span><span class=\"job\">"..vRP.getUserGroupByType(k,"job").."</span>"
                    end
                end

                -- check end
                count = count-1
                if count == 0 then
                    player_lists[player] = true
                    local css = [[
              .div_user_list{
                margin: auto;
				text-align: left;
                padding: 8px;
                width: 650px;
                margin-top: 100px;
                background: rgba(50,50,50,0.0);
                color: white;
                font-weight: bold;
                font-size: 1.1em;
              }
              .div_user_list span{
				display: inline-block;
				text-align: center;
              }
              .div_user_list .id{
                color: rgb(255, 255, 255);
                width: 45px;
              }
              .div_user_list .pseudo{
                color: rgb(66, 244, 107);
                width: 145px;
              }
              .div_user_list .name{
                color: rgb(92, 170, 249);
                width: 295px;
              }
			  .div_user_list .job{
                color: rgb(247, 193, 93);
                width: 145px;
			  }
            ]]
                    vRPclient.setDiv(player,"user_list", css, content)
                end
            end
        end
    end
end

