---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 8/4/2018 14:06
---

police_weapons = {}
police_weapons["Equip"] = {function(player,choice)
    local user_id = vRP.getUserId(player)
    vRPclient.giveWeapons(player,{
        ["WEAPON_COMBATPISTOL"] = {ammo=500},
        ["WEAPON_PUMPSHOTGUN"] = {ammo=500},
        ["WEAPON_PISTOL"] = {ammo=500},
        ["WEAPON_CARBINERIFLE"] = {ammo=500},
        ["WEAPON_NIGHTSTICK"] = {ammo=1},
        ["WEAPON_STUNGUN"] = {ammo=500},
        ["WEAPON_SPECIALCARBINE"] = {ammo=500},
        ["WEAPON_BULLPUPRIFLE"] = {ammo=500},
        ["WEAPON_COMBATPDW"] = {ammo=500},
        ["WEAPON_ADVANCEDRIFLE"] = {ammo=500},
        ["WEAPON_FLASHLIGHT"] = {ammo=1},
        ["WEAPON_SMG"] = {ammo=500},
        ["WEAPON_MICROSMG"] = {ammo=500},
        ["WEAPON_STUNGUN"] = {ammo=500}
    }, true)
    vRPclient.setArmour(player,1000,true)
    vRPclient._notify(player,"You received ~ g ~ received medical equipment")
end}


vRP.registerMenuBuilder("static:policearma",police_weapons)

