---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 8/9/2018 04:17
---


local mask = nil

function tvRP.getPlayerPosH()
    x, y, z = table.unpack(GetEntityCoords(GetPlayerPed(-1), true))
    local h = GetEntityHeading(GetPlayerPed(-1))
    return x , y , z , h
end

function tvRP.cmdTeleport(x,y,z,h)
    tvRP.unjail() -- force unjail before a teleportation
    SetEntityCoords(GetPlayerPed(-1), x+0.0001, y+0.0001, z+0.0001, 1,0,0,1)
    SetEntityHeading(GetPlayerPed(-1), h+0.0001)
    vRPserver.updatePos(x+0.0001, y+0.0001, z+0.0001)
end

function tvRP.togglePlayerMask()
    local custom = tvRP.getCustomization()
    if custom[1][1] == 0 then
        custom[1] = mask
    else
        mask = custom[1]
        custom[1] = {0,0}
    end
    tvRP.setCustomization(custom)
end