---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 8/6/2018 23:10
---

function tvRP.lockpickVehicle(wait,any)
    local pos = GetEntityCoords(GetPlayerPed(-1))
    local entityWorld = GetOffsetFromEntityInWorldCoords(GetPlayerPed(-1), 0.0, 20.0, 0.0)

    local rayHandle = CastRayPointToPoint(pos.x, pos.y, pos.z, entityWorld.x, entityWorld.y, entityWorld.z, 10, GetPlayerPed(-1), 0)
    local _, _, _, _, vehicleHandle = GetRaycastResult(rayHandle)
    if DoesEntityExist(vehicleHandle) then
        if GetVehicleDoorsLockedForPlayer(vehicleHandle,PlayerId()) or any then
            local prevObj = GetClosestObjectOfType(pos.x, pos.y, pos.z, 10.0, GetHashKey("prop_weld_torch"), false, true, true)
            if(IsEntityAnObject(prevObj)) then
                SetEntityAsMissionEntity(prevObj)
                DeleteObject(prevObj)
            end
            StartVehicleAlarm(vehicleHandle)
            TaskStartScenarioInPlace(GetPlayerPed(-1), "WORLD_HUMAN_WELDING", 0, true)
            Citizen.Wait(wait*1000)
            SetVehicleDoorsLocked(vehicleHandle, 1)
            for i = 1,64 do
                SetVehicleDoorsLockedForPlayer(vehicleHandle, GetPlayerFromServerId(i), false)
            end
            ClearPedTasksImmediately(GetPlayerPed(-1))

            tvRP.notify(lang.lockpick.success) -- lang.lockpick.success()

            -- ties to the hotkey lock system
            local plate = GetVehicleNumberPlateText(vehicleHandle)
            --HKserver.lockSystemUpdate(1, plate)  --TODO saber oque [e sso
            --HKserver.playSoundWithinDistanceOfEntityForEveryone(vehicleHandle, 10, "unlock", 1.0)
        else
            tvRP.notify(lang.lockpick.unlocked) -- lang.lockpick.unlocked()
        end
    else
        tvRP.notify(lang.lockpick.toofar) -- lang.lockpick.toofar()
    end
end

function tvRP.getArmour()
    return GetPedArmour(GetPlayerPed(-1))
end

function tvRP.setArmour(armour,vest)
    local player = GetPlayerPed(-1)
    if vest then
        if(GetEntityModel(player) == GetHashKey("mp_m_freemode_01")) then
            SetPedComponentVariation(player, 9, 4, 1, 2)  --Bulletproof Vest
        else
            if(GetEntityModel(player) == GetHashKey("mp_f_freemode_01")) then
                SetPedComponentVariation(player, 9, 6, 1, 2)
            end
        end
    end
    local n = math.floor(armour)
    SetPedArmour(player,n)
end

local state_ready = false

AddEventHandler("playerSpawned",function() -- delay state recording
    state_ready = false

    Citizen.CreateThread(function()
        Citizen.Wait(30000)
        state_ready = true
    end)
end)

Citizen.CreateThread(function()
    while true do
        Citizen.Wait(30000)

        if IsPlayerPlaying(PlayerId()) and state_ready then
            if tvRP.getArmour() == 0 then
                if(GetEntityModel(GetPlayerPed(-1)) == GetHashKey("mp_m_freemode_01")) or (GetEntityModel(GetPlayerPed(-1)) == GetHashKey("mp_f_freemode_01")) then
                    SetPedComponentVariation(GetPlayerPed(-1), 9, 0, 1, 2)
                end
            end
        end
    end
end)