---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 8/9/2018 02:15
---
local cfg = module("cfg/utils/voice_display")
local voice = 1

Citizen.CreateThread(function()
    while true do
        Citizen.Wait(0)
        if IsControlJustPressed(1, cfg.key) then
            voice = voice + 1
            if voice > #cfg.volume then voice = 1 end
            tvRP.setDiv("voice_text",cfg.volume[voice].css,cfg.volume[voice].text)
            tvRP.setDiv("voice_icon",cfg.volume[voice].css,cfg.volume[voice].text)
            NetworkSetTalkerProximity(cfg.volume[voice].distance)
        end
    end
end)

AddEventHandler('playerSpawned', function(spawn)
    tvRP.setDiv("voice_text",cfg.volume[voice].css,cfg.volume[voice].text)
    tvRP.setDiv("voice_icon",cfg.volume[voice].css,cfg.volume[voice].text)
    NetworkSetTalkerProximity(cfg.volume[voice].distance)
end)