---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 8/5/2018 11:13
---

local permlang = {
    player = {
        player_list = "player.list",
        addgroup = "player.group.addperm",
        addgroup_code =  "add.group.{1}",
        removegroup =  "player.group.remove",
        removegroup_code = "add.group.{1}"
    },
    police = {},
    emergency = {},
    admin = {
        whilelist = "player.whitelist",
        unwhitelist = "player.unwhitelist",
        addgroup = "player.group.add",
        removegroup = "player.group.remove",
        kick = "player.kick",
        ban = "player.ban",
        unban = "player.unban",
        emote = "player.custom_emote",
        sound = "player.custom_sound",
        menu = {
            player_list = "player.list",
            whitelist = "player.whitelist",
            addgroup = "player.group.add",
            removegroup = "player.group.remove",
            unwhitelist = "player.unwhitelist",
            kick = "player.kick",
            ban = "player.ban",
            unban = "player.unban",
            noclip = "player.noclip",
            custom_emote = "player.custom_emote",
            custom_sound = "player.custom_sound",
            custom_audiosource = "player.custom_sound",
            coords = "player.coords",
            tptome = "player.tptome",
            tpto =  "player.tpto",
            tptp = "player.tpto",
            givemoney = "player.givemoney",
            giveitem = "player.giveitem",
            display_custom = "player.display_custom",
            calladmin ="player.calladmin",
            god = "admin.god"
        }

    }
}

return permlang
