---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 8/3/2018 17:38
---
--local lang = module("lib/Itemluang")
local items = {}

--[[
local function bvest_choices(args)
    local choices = {}

    choices[lang.bodyarmor.equip()] = {function(player, choice)
        local user_id = vRP.getUserId(player)
        if user_id then
            if vRP.tryGetInventoryItem(user_id, lang.lockpick.id(), 1, true) then -- take vest
                vRPclient._lockpickVehicle(player,20,true) -- 20s to lockpick, allow to carjack unlocked vehicles (has to be true for NoCarJack Compatibility)
                --Todo cliente version desse
                vRP.closeMenu(player)
            end
        end
    end}

    return choices
end

items[lang.lockpick.id()] = {lang.lockpick.name(), lang.lockpick.desc(), bvest_choices, 0.75}
]]  --todo fixar isso



return items
