---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 8/6/2018 23:34
---
local lang = vRP.lang
Citizen.CreateThread(function()
    vRP.registerMenuBuilder("phone", function(add) -- phone menu is created on server start, so it has no permissions.
        Citizen.CreateThread(function()
            local choices = {} -- Comment the choices you want to disable by adding -- in front of them.

            choices[lang.mpay.button()] = ch_mobilepay -- transfer money through phone
            choices[lang.mcharge.button()] = ch_mobilecharge -- charge money through phone

            add(choices)
        end)
    end)
end)