---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 8/6/2018 23:37
---

local lang = vRP.lang

Citizen.CreateThread(function()
    vRP.registerMenuBuilder("police_weapons", police_weapons) -- police gear
    vRP.registerMenuBuilder("emergency_medkit", emergency_medkit) -- pills and medkits
    vRP.registerMenuBuilder("emergency_heal", emergency_heal) -- heal button
end)