---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 8/4/2018 18:41
---
local cfg = {}

cfg.currencyReset = 12*60
cfg.currencyEspecialReset = 24*60
cfg.fixerApikey = "85bfaa39fcdd1de13da51989a4c492ca"

return cfg