---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 8/26/2018 01:09
---
local cfg = {}


cfg.tax = {
    ICMS = 1.18,
    ISS = 1.18,
    IPI = 1.25,
    II = 1.11,
    PIS = 1.12,
    COFINS = 1.14,
}

return cfg