---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 8/8/2018 14:06
---

local cfg = {}

cfg.chance = 50 -- chance of being unlocked in percentage

cfg.blacklist = { -- vehicles that will always be locked when spawned naturally
    "T20",
    "RHINO"
}

return cfg