---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 8/4/2018 21:29
---
local lang = vRP.lang
local perm = vRP.permLang

local function ch_tptowaypoint(player, choice)
    local user_id = vRP.getUserId(player)
    if user_id then
        vRPclient._tpToWayPoint(player)
    end
end

local function ch_blips(player, choice)
    local user_id = vRP.getUserId(player)
    if user_id then
        vRPclient._showBlips(player)
    end
end

local function ch_deleteveh(player, choice)
    local user_id = vRP.getUserId(player)
    if user_id then
        vRPclient._deleteVehicleInFrontOrInside(player, 5.0)
    end
end

local function ch_godmode(player, choice)
    local user_id = vRP.getUserId(player)
    if user_id ~= nil then
        if gods[player] then
            gods[player] = nil
            vRPclient._notify(player, lang.admin.menu.godmode.off())
        else
            gods[player] = user_id
            vRPclient._notify(player, lang.admin.menu.godmode.on())
        end
    end
end

local function ch_spawnveh(player, choice)
    local model = vRP.prompt(player, lang.admin.spawnveh.prompt(), "")
    if modle ~= nil and model ~= "" then
        vRPclient._spawnVehicle(player, model)
    else
        vRPclient._notify(player, lang.common.invalid_value())
    end
end

local function ch_addgroupperm(player, choice)
    local user_id = vRP.getUserId(player)
    if user_id ~= nil and vRP.hasPermission(user_id, perm.player.addgroup()) then
        local id = vRP.prompt(player, lang.admin.menu.addgroup.prompt_id(), "")
        id = parseInt(id)
        if vRP.hasIDExist(id) then
            local group = vRP.prompt(player, lang.admin.menu.addgroup.prompt(), "")
            if group then
                if not vRP.hasGroup(id, group) then
                    if vRP.getGroupCheck(group) then
                        local groupcode = vRP.getGroupCode(group)
                        if vRP.hasPermission(id, perm.player.addgroup_code({groupcode})) then
                            vRP.addUserGroup(id, group)
                            vRPclient._notify(player, lang.admin.menu.addgroup.notify({ group, id }))
                        else
                            vRPclient._notify(player, lang.common.not_perm())
                        end
                    else
                        vRPclient._notify(player, lang.common.invalid_group())
                    end
                else
                    vRPclient._notify(player, lang.admin.menu.addgroup.already())
                end
            end
        else
            vRPclient._notify(player, lang.common.invalid_id())
        end
    end
end

local function ch_removegroupperm(player, choice)
    local user_id = vRP.getUserId(player)
    if user_id and vRP.hasPermission(user_id, perm.player.removegroup()) then
        local id = vRP.prompt(player, lang.admin.menu.removegroup.prompt(), "")
        id = parseInt(id)
        if vRP.hasIDExist(id) then
            local group = vRP.prompt(player, lang.admin.menu.removegroup.prompt(), "")
            if group then
                if vRP.hasGroup(id, group) then
                    if vRP.getGroupCheck(group) then
                        local groupcode = vRP.getGroupCode(group)
                        if vRP.hasPermission(id, perm.player.removegroup_code({groupcode})) then
                            vRP.removeUserGroup(id, group)
                            vRPclient._notify(player, lang.admin.menu.removegroup.notify({ group, id }))

                        else
                            vRPclient._notify(player, lang.common.not_perm())
                        end
                    else
                        vRPclient._notify(player, lang.common.invalid_group())
                    end
                else
                    vRPclient._notify(player, lang.admin.menu.removegroup.not_found({group}))
                end
            end
        else
            vRPclient._notify(player, lang.common.invalid_id())
        end
    end
end