---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 8/5/2018 11:13
---

local permlang = {
    player = {
        player_list = "player.list",
        addgroup = "player.group.addperm",
        addgroup_code =  "add.group.{1}",
        removegroup =  "player.group.remove",
        removegroup_code = "add.group.{1}"
    },
    police = {},
    emergency = {},
    dev = {
        menu = "player.givemoney",
        crun = "player.givemoney",
        srun = "player.givemoney",
    },
    admin = {
        whilelist = "player.whitelist",
        unwhitelist = "player.unwhitelist",
        addgroup = "player.group.add",
        removegroup = "player.group.remove",
        kick = "player.kick",
        ban = "player.ban",
        adv_ban = "player.ban",
        appeal = "player.unban",
        unban = "player.unban",
        emote = "player.custom_emote",
        sound = "player.custom_sound",
        god ="admin.god",
        menu = {
            player_list = "player.list",
            whitelist = "player.whitelist",
            addgroup = "player.group.add",
            removegroup = "player.group.remove",
            unwhitelist = "player.unwhitelist",
            kick = "player.kick",
            ban = "player.ban",
            adv_ban = "player.ban",
            appeal = "player.unban",
            ban_check = "player.ban",
            unban = "player.unban",
            noclip = "player.noclip",
            custom_emote = "player.custom_emote",
            custom_sound = "player.custom_sound",
            custom_audiosource = "player.custom_sound",
            coords = "player.coords",
            tptome = "player.tptome",
            tpto =  "player.tpto",
            tptp = "player.tpto",
            givemoney = "player.givemoney",
            givemoney_to = "player.givemoney",
            givemoney_usd = "player.givemoney",
            givemoney_to_usd = "player.givemoney",
            givemoney_eur = "player.givemoney",
            givemoney_to_eur = "player.givemoney",
            givemoney_btc = "player.givemoney",
            givemoney_to_btc = "player.givemoney",
            giveitem = "player.giveitem",
            display_custom = "player.display_custom",
            calladmin ="player.calladmin",
            god = "admin.god",
            addgroup_perm = "player.group.add",
            removegroup_perm = "player.group.remove",
            report = "player.givemoney",
            tptowaypoint = "player.givemoney",
            blips = "player.givemoney",
            deleteveh = "player.givemoney",
            godmode = "player.givemoney",
            spawnveh = "player.givemoney",

        }

    }
}

return permlang
