---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 8/5/2018 04:31
---


local lang = {
    common = {
        invalid_model = "Model invalid"
    },
    vehicle = {
        unlock = "Vehicle Unlocked.",
        locked = "Vehicle locked",
        veh_already_spawn = "This vehicle is already out.",
        veh_stored = "Vehicle stored."
    },
    phone = {
      voice_callback ="(vRPvoice-phone) requested by ",
      voice_connected = "(vRPvoice-phone) connected to ",
      voice_disconnected = "(vRPvoice-phone) disconnected from "
    },
    radio = {
        callback = "(vRPvoice-radio) requested by ",
        connected = "(vRPvoice-radio) connected to ",
        disconnected = "(vRPvoice-radio) disconnected from "
    },
    voip = {
        callback = "(vRPvoice-world) requested by ",
        connected = "(vRPvoice-world) connected to ",
        disconnected ="(vRPvoice-world) disconnected from ",
        register = {
            voip_channel = "[vRP] VoIP channel callbacks for ",
            already = "already registered.",
        }
    },
    tptowaypoint = {
        notfound = "Waypoint not found!",
        success = "You are teleport!"
    },
    spawnveh = {
        load = "Loading",
        success = "The vehicle was spawned"
    },
    deleteveh = {
        success = "Vehicle was deleted",
        toofar = "Too far from vehicle"
    },
    blips = {
        on = "Blips is ON",
        off = "Blips is OFF"
    },
    sprite =  {
        on = "Sprites ON",
        off = "Sprites OFF"
    }

}

return lang