---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 8/5/2018 04:31
---


local lang = {
    vehicle = {
        unlock = "Vehicle Unlocked.",
        locked = "Vehicle locked"
    },
    phone = {
      voice_callback ="(vRPvoice-phone) requested by ",
      voice_connected = "(vRPvoice-phone) connected to ",
      voice_disconnected = "(vRPvoice-phone) disconnected from "
    },
    radio = {
        callback = "(vRPvoice-radio) requested by ",
        connected = "(vRPvoice-radio) connected to ",
        disconnected = "(vRPvoice-radio) disconnected from "
    },
    voip = {
        callback = "(vRPvoice-world) requested by ",
        connected = "(vRPvoice-world) connected to ",
        disconnected ="(vRPvoice-world) disconnected from ",
        register = {
            voip_channel = "[vRP] VoIP channel callbacks for ",
            already = "already registered.",
        }
    }

}

return lang