---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 8/25/2018 23:26
---
local cfg = module("cfg/utils/economy")

vRP.economy = {
    ICMS = cfg.tax.ICMS,
    ISS = cfg.tax.ISS,
    IPI = cfg.tax.IPI,
    II = cfg.tax.II,
    PIS = cfg.tax.PIS,
    COFINS = cfg.tax.COFINS,

}



function vRP.getICMS()
    return vRP.economy.ICMS
end

function vRP.getISS()
    return vRP.economy.ISS
end

function vRP.getIPI()
    return vRP.economy.IPI
end

function vRP.getII()
    return vRP.economy.II
end

function vRP.getPIS()
    return vRP.economy.PIS
end

function vRP.getCOFINS()
    return vRP.economy.COFINS
end