---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 8/7/2018 01:46
---
-- unfreeze on spawn
AddEventHandler("vRP:playerSpawn", function(user_id, source, first_spawn)
    if not first_spawn then
        local address = vRP.getUserAddress(user_id)
        if address then
            SetTimeout(5000,function()
                vRP.accessHome(user_id, address.home, address.number)
            end)
        end
    end
end)
