---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 8/3/2018 03:46
---
local config = module("cfg/base")
local time_file_format = os.date("%d-%m-%Y")
local dir = cfg._inv

function vRP.makeLogFolders()
    os.execute("mkdir"..dir.."ServerLog\\AntiRP_REPORTS")
    os.execute("mkdir"..dir.." ServerLog\\Weapons_Shot")
    os.execute("mkdir"..dir.." ServerLog\\Player\\LoginHistory")
    os.execute("mkdir"..dir.." ServerLog\\Player\\kills")
    os.execute("mkdir"..dir.." ServerLog\\Player\\money")
    os.execute("mkdir"..dir.."ServerLog\\Player\\jobs")
    os.execute("mkdir"..dir.." ServerLog\\Player\\police_weapons_get")
    os.execute("mkdir"..dir.." ServerLog\\Player\\jail")
    os.execute("mkdir"..dir.." ServerLog\\chat\\global")
    os.execute("mkdir"..dir.." ServerLog\\chat\\twitter")
    os.execute("mkdir"..dir.." ServerLog\\chat\\occ")
    os.execute("mkdir"..dir.." ServerLog\\Police\\police_weapons_get")
    os.execute("mkdir"..dir.." ServerLog\\Police\\jail")
end

--ToDo Quando o player logar, criar uma pasta de log dele.


function vRP.logInfoToFile(file,info)
    file = io.open(file,"a")
    if file then
        file:write(os.date("%c").."=> "..info.. "\n")
    end
    file:close()
end

function vRP.logWeaponsShot(user_id,weapons,location)
    local file = io.open(config.cfg.home_dir.."/ServerLog/Weapons_shot/"..time_file_format..".txt","a")
    if file then
        file:write("["..os.date("%c")"] ID: "..user_id.."has shoting with "..weapons.." in "..location .."\n")
    end
    file:close()
end
--todo Implementacao
function vRP.logAntiRPReport() end

function vRP.logPlayerLoginHistory(user_id, ip, steam_id, fivemid)
    local file = io.open(config.cfg.home_dir.. "/ServerLog/Player/LoginHistory/"..user_id.."/".. time_file_format..".txt", "a")
    if file then
        file:write("["..os.date("%c")"] ID: "..user_id.."User logged in on steam "..steam_id.." with ip "..ip.." and fivemid: "..fivemid..".")
    end
    file:close()
end

function vRP.logPlayerKills(user_id, location, player, weapons)
    local file = io.open(config.cfg.home_dir.."/ServerLog/Player/kills"..user_id.."/"..time_file_format..".txt", "a")
    if file then
        file:write("["..os.date("%c")"] ID: "..user_id.."The user killed the player "..player.." using "..weapons.." on the spot(location) "..location..".")
    end
    file:close()
end

function vRP.logPlayerMoney(user_id, money)
    local file = io.open(config.cfg.home_dir.."ServerLog/Player/money"..user_id.."/"..time_file_format..".txt", "a")
    if file then
        file:write("["..os.date("%c")"] ID: "..user_id.."The user has the amount of "..money..".")
    end
    file:close()
end

function vRP.logPlayerJobs(user_id, jobs)
    local file = io.open(config.cfg.home_dir.."ServerLog/Player/jobs"..user_id.."/"..time_file_format..".txt", "a")
    if file then
        file:write("["..os.date("%c")"] ID: "..user_id.."The user the works from: "..jobs..".")
    end
    file:close()
end

function vRP.logPlayerPoliceWeaponsGet(user_id, weapons)
    local file = io.open(config.cfg.home_dir.."ServerLog/Player/police_weapons_get"..user_id.."/"..time_file_format..".txt", "a")
    if file then
        file:write("["..os.date("%c")"] ID: "..user_id.."This cop has the weapons: "..weapons..".")
    end
    file:close()
end

function vRP.logPlayerJail(user_id, player)
    local file = io.open(config.cfg.home_dir.."ServerLog/Player/jail"..user_id.."/"..time_file_format..".txt", "a")
    if file then
        file:write("["..os.date("%c")"] ID: "..user_id.."The user was caged by "..player..".")
    end
    file:close()
end

function vRP.logChatGlobal(user_id, message)
    local file = io.open(config.cfg.home_dir.."ServerLog/chat/global"..user_id.."/"..time_file_format..".txt", "a")
    if file then
        file:write("["..os.date("%c")"] ID: "..user_id.."The user chatted: "..message..".")
    end
    file:close()
end

function vRP.logChatTwitter(user_id, message)
    local file = io.open(config.cfg.home_dir.."ServerLog/chat/twitter"..user_id.."/".time_file_format..".txt", a)
    if file then
        file:write("["..os.date("%c")"] ID: "..user_id.."The user chatted: "..message..".")
    end
    file:close()
end

function vRP.logChatOCC(user_id, message)
    local file = io.open(config.cfg.home_dir.."ServerLog/chat/occ"..user_id.."/"..time_file_format..".txt", "a")
    if file then
        file:write("["..os.date("%c")"] ID: "..user_id.."The user chatted: "..message..".")
    end
    file:close()
end

function vRP.logPoliceWeaponsGet(user_id, weapons)
    local file = io.open(config.cfg.home_dir.."ServerLog/police/police_weapons_get"..user_id.."/"..time_file_format..".txt", "a")
    if file then
        file:write("["..os.date("%c")"] ID:"..user_id.."The policeman took the gun "..weapons..".")
    end
    file:close()
end

function vRP.logPoliceSendJail(user_id, player)
    local file = io.open(config.cfg.home_dir.."ServerLog/police/jail"..user_id.."/"..time_file_format..".txt", a)
    if file then
        file:write("["..os.date("%c")"] ID:"..user_id.."The policeman caged player "..player..".")
    end
    file:close()
end



