---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 8/9/2018 01:54
---

function vRP.updateUserMoney(worth)
    local user_id = vRP.getUserId(source)
    vRP.giveMoney(user_id,worth)
end