---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 8/8/2018 14:03
---

local vehicles = {}
function vRP.setVehicleDoorsForEveryone(veh, doors, plate)
    if not vehicles[plate] then
        local user_id = vRP.getUserId(source)
        local identity = vRP.getUserIdentity(user_id)
        local user_plate = "P " .. identity.registration
        if user_plate ~= plate then
            local users = vRP.getUsers()
            for k,v in pairs(users) do
                vRPclient.setVehicleDoors(v,veh, doors)
            end
        end
        vehicles[plate] = true
    end
end