---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 8/13/2018 23:08
---
local uuid = module("lib/uuid")

function vRP.generateUUID()
    local uuid4 = module("lib/uuid4")
    return uuid4.getUUID()
end