---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 8/3/2018 06:14
---

local Itemlang = {
    bodyarmor = {
        id = "body_armor",
        name = "Body Armor",
        desc = "Intact body armor.",
        equip = "Equip",
        damaged = "That body armor is damaged.",
        store = {
            button = "Store Body Armor",
            perm = "store.bodyarmor",
            desc = "Store body armor.",
        },
    },
    lockpick = {
        id = "lockpicking_kit",
        name = "Lockpicking Kit",
        button = "Lockpick",
        perm = "carjacker.lockpick",
        desc = "Lockpick nearby vehicle.",
        success = "~g~Vehicle unlocked.",
        toofar = "~r~Too far away from vehicle.",
        unlocked = "~g~Vehicle already unlocked.",
    }

}


return itemlang